[project]
name = "chapter-4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ginza>=5.2.0",
    "ja-ginza>=5.2.0",
    "matplotlib>=3.10.7",
    "spacy>=3.8.11",
]
